version: '3.8'

services:
  mysql:
    image: mysql:latest
    env_file:
      - ./data/.env
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./data/00-database.sql:/docker-entrypoint-initdb.d/00-database.sql
